sudo: required
services:
   - docker

before_install:
  - docker build -t mohsin1708/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mohsin1708/react-test npm test

after_success:
  - docker build -t mohsin1708/multi-client ./client
  - docker build -t mohsin1708/multi-nginx ./nginx
  - docker build -t mohsin1708/multi-server ./server
  - docker build -t mohsin1708/multi-worker ./worker
  # Login into docker
  - echo "$Docker_password" | docker login -u "$Docker_id" --password-stdin
  # Take those push images
  - docker push mohsin1708/multi-client
  - docker push mohsin1708/multi-nginx
  - docker push mohsin1708/multi-server
  - docker push mohsin1708/multi-worker
